### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by andrr2** [michaeltukdev/AetherBilling#8]
Hello! I want to test this billing software, how to install it ?
Thanks!

**Comment by mtiluk** [comment]
Hey,

This is still in development and I wouldn't suggest using it in production as there is still extremely limited functionality. I will make a commit soon including a Docker file.

Otherwise, you'll need dependencies such as `npm`, `composer`, `php`, and a database (You can edit the .env to use sqlite).

I am active on Discord if you would like to keep up to date with progress or get any assistance in testing.
